// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace FastDate
{
    internal static unsafe partial class NativeMethods
    {
        const string __DllName = "fastdate";





        /// <summary>
        ///  Parse the iso datetime into a packed datetime object (NEON).
        ///  # Safety
        ///
        ///  This method assumes input is in the correct ISO 8601 format.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "parse_iso_date_neon", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PackedDateTime parse_iso_date_neon(byte* input);

        /// <summary>
        ///  Parse the iso datetime into a packed datetime object (SSE3).
        ///  # Safety
        ///
        ///  This method assumes input is in the correct ISO 8601 format.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "parse_iso_date_sse", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        internal static extern PackedDateTime parse_iso_date_sse(byte* input);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct PackedDateTime
    {
        public uint date;
        public uint time;
    }



}
